jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8082
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe    
    username: SYSTEM
    password: MARIANO
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true    
    #hibernate:
      #ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle8iDialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false